Odyssey2Frontend/Controllers/PrintshopResourcesTemplateController.cs
/*TASK RP. RESOURCES*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Odyssey2Frontend.Models;

//                                                          //AUTHOR: Towa (VSTD - Victor Torres).
//                                                          //CO-AUTHOR: Towa (LGF-Liliana Gutierrez).
//                                                          //DATE: December 19, 2019.

namespace Odyssey2Frontend.Controllers
{
    //==================================================================================================================
    public class PrintshopResourcesTemplateController : BaseController
    {
        //-------------------------------------------------------------------------------------------------------------
        /*STATIC VARIABLES*/

        static List<PrintshopProcessTemplateModel> darrstrProcessTemplate { get; set; }

        //--------------------------------------------------------------------------------------------------------------
        //                                                  //CONSTRUCTORS.

        //--------------------------------------------------------------------------------------------------------------
        public PrintshopResourcesTemplateController(AppSessionContext requestHandler, IConfiguration iConfiguration)
            : base(requestHandler, iConfiguration)
        {
        }

        //--------------------------------------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<ResourceModel> darrresource = new List<ResourceModel>();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            if (
                //                                          //If the printshopId is not null.
                !String.IsNullOrEmpty(this.strPrintshopId)
                )
            {
                HttpResponseMessage response = await client.GetAsync(
                    configuration.GetValue<String>("Odyssey2Settings:serviceAddress")
                    + $"/Type/GetPrintshopTypes?strPrintshopId={ this.strPrintshopId }" +
                    $"&strResOrPro=Resource&boolnIsPhysical=true");

                String strResult;
                if (response.IsSuccessStatusCode)
                {
                    strResult = await response.Content.ReadAsStringAsync();

                    JsonResponseModel JsonResponseModel = JsonSerializer.Deserialize<JsonResponseModel>(strResult);
                    JsonResponseModel.objResponse = JsonSerializer
                        .Deserialize<List<ResourceModel>>(JsonResponseModel.objResponse.ToString());

                    if (JsonResponseModel.intStatus == 200)
                    {
                        darrresource = (List<ResourceModel>)JsonResponseModel.objResponse;
                    }
                }
            }

            ViewBag.strPrintshopId = this.strPrintshopId;
            return View(darrresource);
        }

        //--------------------------------------------------------------------------------------------------------------
        public async Task<IActionResult> AddXJDF(bool boolIsPhysical)
        {
            List<PrintshopProcessTemplateModel> darrXJDFProcess = await subGetPrintshopXJDFProcess();
            ViewBag.darrXJDFProcess = new SelectList(darrXJDFProcess.Select(
                    s => new PrintshopProcessTemplateModel
                    {
                        intPk = s.intPk,
                        strTypeId = s.strTypeId
                    }
                ),
                "intPk", "strTypeId");

            if(
                boolIsPhysical
                )
            {
                await subGetResourcesClassification();
            }

            await GetResourcesByProcessOrAll("All", "All", boolIsPhysical);

            ViewBag.strPrintshopId = this.strPrintshopId;
            ViewBag.boolIsPhysical = boolIsPhysical;

            return View();
        }

        //--------------------------------------------------------------------------------------------------------------
        public async Task<IActionResult> GetResourcesByProcessOrAll(
            String strProcess, 
            String strClasification, 
            bool boolIsPhysical)
        {
            IActionResult aresult;

            if(strClasification == null)
            {
                strClasification = "Parameter";
            }

            if (strProcess == "All")
            {
                List<ResourceModel> darrXJDFResource = new List<ResourceModel>();
                darrXJDFResource = await subGetPrintshopXJDFResources(boolIsPhysical);
                if (strClasification != "All")
                {
                    darrXJDFResource = darrXJDFResource.Where(w => w.strClassification == strClasification).ToList();
                }
                ViewBag.darrXJDFResource = darrXJDFResource;
                aresult = base.Ok(darrXJDFResource);
            }
            else
            {
                ResourceModel XJDFResource = new ResourceModel();
                XJDFResource = await subGetPrintshopXJDFResourcesByProcess(Convert.ToInt32(strProcess), boolIsPhysical);

                List<ResourcesByProcessModel> resXJDFResourceList = XJDFResource.arrres;
                if (strClasification != "All")
                {
                    resXJDFResourceList = resXJDFResourceList.Where(w => w.strClassification == strClasification).ToList();
                }
                aresult = base.Ok(resXJDFResourceList);
            }

            return aresult;
        }

        //--------------------------------------------------------------------------------------------------------------
        [HttpGet]
        public async Task<ActionResult> GetAscendantsValuesResource(int intPkType)
        {
            ActionResult aresult = BadRequest("Invalid data.");

            List<MyResourcesModel> darrmyResourcesModel = await subGetResources(intPkType);

            ViewBag.intPkTemplate = intPkType;

            aresult = PartialView("GetAscendantsValuesResourcePartialView", darrmyResourcesModel);

            return aresult;
        }

        //--------------------------------------------------------------------------------------------------------------
        public async Task<IActionResult> GetTemplatesAndResources(int intPk, bool boolIsType)
        {
            IActionResult aresult = BadRequest("Invalid data.");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            ObjTemplatesAndResourcesResponse templatesAndResources = new ObjTemplatesAndResourcesResponse();

            HttpResponseMessage response = await client.GetAsync(
                    configuration.GetValue<String>("Odyssey2Settings:serviceAddress")
                    + $"/resource/GetAttributesTemplatesAndresources?intPk={intPk}&boolIsType={boolIsType}");

            if (response.IsSuccessStatusCode)
            {
                String strResult = await response.Content.ReadAsStringAsync();
                templatesAndResources = JsonSerializer
                        .Deserialize<ObjTemplatesAndResourcesResponse>(strResult);

                if (
                    templatesAndResources.intStatus == 200
                    )
                {
                    aresult = View("GetTemplatesAndResources", templatesAndResources);
                }
                else { 
                    aresult = RedirectToAction("index");
                }
            }

            ViewBag.boolDefaultCalculationResource = true;
            return aresult;
        }

        //--------------------------------------------------------------------------------------------------------------
        public async Task<IActionResult> AddXJDFForm(int intPkType, String strType,
            int intPkResource, int intnPkTemplate, bool boolIsPhysical, bool? boolnIsChangeable, 
            bool? boolIsDeviceToolOrCustom)
        {
            List<TemplateModel> darrTemplates = await subGetTemplates(intPkType);
            List<MyResourcesModel> darrmyResources = await subGetResources(intPkType);
            EditResourceModel jsonResponseModel = new EditResourceModel();
            jsonResponseModel.intPkType = intPkType;
            jsonResponseModel.strTypeName = strType;
            jsonResponseModel.intPkResource = intPkResource;
            jsonResponseModel.intnPkInherited = intnPkTemplate > 0 ? intnPkTemplate : 0;
            jsonResponseModel.boolIsPhysical = boolIsPhysical;
            jsonResponseModel.boolnIsChangeable = boolnIsChangeable;
            jsonResponseModel.boolnIsDeviceToolOrCustom = boolIsDeviceToolOrCustom;

            ViewBag.darrTemplates = new SelectList(
                    darrTemplates.Select(s => new SelectListItem
                    {
                        Text = s.strTypeId,
                        Value = s.intPk.ToString()
                    }),
                    "Value",
                    "Text",
                    jsonResponseModel.intnPkInherited
                    );

            ViewBag.darrTemplatesForInherit = new SelectList(
                    darrTemplates.Select(s => new SelectListItem
                    {
                        Text = s.strTypeId,
                        Value = s.intPk.ToString()
                    }),
                    "Value",
                    "Text"
                    );

Odyssey2Frontend/Views/PrintshopResourcesTemplate/AddCustomResourceTemplatePartialView.cshtml
<div class="row">
    <div class="col-sm-5">
        <label class="input-label">Resource Name</label>
        <input class="form-control input-with-dropdowns" name="strResourceName" id="strResourceName"
               placeholder="Resource Name">
    </div>
    <div class="col-sm-4">
        <label class="input-label">Unit of Measurement</label>
        <input type="text" id="strUnitCustomResource" name="strUnit" autocomplete="off"
               class="busca form-control input-with-dropdowns showUnits" />
        <div id="display" class="unitsList mt-0 pl-1 pr-0"
             style="font-family: 'Rawline Regular', sans-serif; color: #58585b; font-size: 14px; border-radius:0px;">

        </div>
    </div>
    <div class="col-sm-3">
        <label class="form-check-label checkbox-label" style="margin-left: 30px; margin-top:30px;">
            <input type="checkbox" class="form-check-input chkDecimal" id="boolIsDecimal"
                   name="boolIsDecimal">Use decimals
        </label>
    </div>
    <div class="col-sm-12">
        <div class="row pull-right">
            <div>
                <button type="button" class="btn btn-block btn-sm btn-primary mb-0" id="saveCustomResource" 
                    style="margin-top: 30px" hidden>Save</button>
            </div>
            <div>
                <button type="button" class="btn btn-info btn-sm ml-2 mb-0" id="addNewCustomResourceAttr"
                        style="margin-top: 30px">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i> Add attribute
                </button>
            </div>
        </div>
    </div>
    <div class="col-sm-12 card-body" id="dinamicCustomResourceAttributes" style="overflow-y: scroll; height: 53vh">
        <form class="border p-3" id="customResourceAttribute-1">
            <div class="form-group row">
                <div class="col-sm-5">
                    <label class="input-label">Attribute Name</label>
                    <input name="strCustomAttrName" class="form-control input-with-dropdowns">
                </div>
                <div class="col-sm-5">
                    <label class="input-label">Value</label>
                    <input name="strCustomValue" class="form-control input-with-dropdowns">
                </div>
                <div class="col-sm-2 text-right p-1">
                    <br>
                    <button type="button" class="btn btn-danger btn-sm removeResourceForm" data-res-card="1">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
        </form><br />
    </div>
</div>

Odyssey2Frontend/Views/PrintshopResourcesTemplate/AddXJDF.cshtml
@*@{
        Html.RenderPartial("AddXJDFPartialView");
    }*@

@{
    ViewData["Title"] = "AddXJDF";
}

<div class="fixed-top border border-top-0" style="margin-top: 75px; background-color: white" id="addXJDFResourceMenu">
    <div class="row">
        <div class="col-sm-9">
            <form class="form-inline">
                <div class="form-group">
                    <div>
                        <label class="checkbox-label">Suggested to Process:</label>
                    </div>
                    <input type="hidden" value="@ViewBag.boolIsPhysical.ToString()" id="boolIsPhysical" />
                    <span class="select ml-2">
                        <select id="intPkProcessSelect" asp-items="@ViewBag.darrXJDFProcess">
                            <option value="All">See All</option>
                        </select>
                    </span>
                    @if ((bool)ViewBag.boolIsPhysical)
                    {
                        <div class="ml-3">
                            <label class="checkbox-label ml-2">Classification:</label>
                        </div>
                        <span class="select ml-2">
                            <select id="strClasificationSelect" asp-items="@ViewBag.Clasification">
                                <option value="All">See All</option>
                            </select>
                        </span>
                    }
                </div>
            </form>
        </div>
        <div class="col-sm-3	">
            <div class="form-group pull-right p-1">
                <a href="" class="btn btn-primary btn-sm float-right" id="resNextStep" hidden>
                    Next <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
                <a type="button" asp-controller="PrintshopResourcesTemplate" asp-action="Index" class="btn btn-secondary btn-sm float-right mr-3">
                    <i class="fa fa-angle-left" aria-hidden="true"></i> Back
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row pt-4" id="chkResources">
    @if (
  ViewBag.darrXJDFResource != null &&
  ViewBag.darrXJDFResource.Count > 0
)
    {
        int i = 0;
        foreach (ResourceModel resourceModel in ViewBag.darrXJDFResource)
        {
            i++;
            <div class="col-sm-4 checkbox">
                <div class="custom-control custom-radio">
                    <input type="radio" class="template-radio custom-control-input"
                           data-boolIsPhysical="@resourceModel.boolIsPhysical"
                           data-checkbox-text="@resourceModel.strTypeId"
                           id="resRadio_@i" name="rdoResource" value="@resourceModel.intPk">
                    <label class="custom-control-label" for="resRadio_@i">@resourceModel.strTypeId</label>
                </div>
            </div>
        }
    }
</div>
<div class="fixed-bottom modal-footer" style="background-color: white; margin-bottom: 0">

</div>

Odyssey2Frontend/Views/PrintshopResourcesTemplate/GetTemplatesAndResources.cshtml
@model Odyssey2Frontend.Models.ObjTemplatesAndResourcesResponse
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
	String strPrintshopId = HttpContextAccessor.HttpContext.Session.GetString("strPrintshopId");
}
<div class="row mb-3">
	<div class="col-sm-6">
		<h2 class="float-left">My Resources</h2>
	</div>
	<div class="col-sm-6">
		<a class="btn btn-secondary btn-sm float-right" href="/PrintshopResourcesTemplate">
			<i class="fa fa-angle-left" aria-hidden="true"></i> Back
		</a>
	</div>
</div>

@if (Model.intStatus == 200)
{
	<input type="hidden" value="@Model.objResponse.boolIsPhysical.ToString().ToLower()" id="boolIsPhysical" />
	<input type="hidden" value="@Model.objResponse.boolIDeviceToolOrCustom.ToString().ToLower()"
		   id="boolIsDeviceToolOrCustom" />
	<ul class="breadcrumb resPath">
		@foreach (var item in Model.objResponse.arrpePathElement)
		{
			<li class="breadcrumb-item">
				<a class="cursor-pointer my-resources"
				   asp-controller="PrintshopResourcesTemplate"
				   asp-action="GetTemplatesAndResources"
				   asp-route-intPk="@item.intPk"
				   asp-route-boolIsType="@item.boolIsType">
					@if (item.boolIsResource)
					{
						<span class="font-bold">@item.strName</span>
					}
					else
					{
						@item.strName
					}
				</a><input class="resBreadcrumb" type="hidden" value="@item.intPk|@item.boolIsType|@item.strName"
						   id="intPkResource" />
			</li>
		}
	</ul>
	if (Model.objResponse.arrattr.Count > 0)
	{
		<h3>Attributes</h3>
		<div class="table-responsive">
			<table class="table" style="text-align: center">
				<thead>
					<tr>
						<th style="text-align: center; font-size:16px;">Attribute</th>
						<th style="text-align: center; font-size:16px;">Value</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model.objResponse.arrattr)
					{
						<tr>
							<td>@item.strName</td>
							<td>@item.strValue</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	}
	@*<hr/>*@
	@if (Model.objResponse.arrtem.Count > 0)
	{
		<h3>Templates</h3>
		<ul class="list-group">
			@foreach (var item in Model.objResponse.arrtem)
			{
				<li class="list-group-item d-flex justify-content-between align-items-center
                    list-group-item-action cursor-pointer">
					<a class="col-sm-9 pt-3 pb-3 my-resources"
					   asp-controller="PrintshopResourcesTemplate"
					   asp-action="GetTemplatesAndResources"
					   asp-route-intPk="@item.intPk"
					   asp-route-boolIsType="@item.boolIsType">@item.strName</a>
					<input type="hidden" value="@item.intPk|@item.boolIsType" id="intPkResource" />
					<span class="">
						@if (Model.objResponse.boolIsPhysical)
						{
							<span class="btn-group">
								@if (!item.boolnIsCalendar.Value && item.boolnIsAvailable != null)
								{
									<span class="btn btn-tertiary">
										<label for="resource-switch-@item.intPk"
											   style="margin-bottom: 0; vertical-align: top;">
											<i class="fa fa-database"></i>
										</label>
									</span>
									@if (Model.objResponse.boolIDeviceToolOrCustom)
									{
										<button type="button" class="btn btn-tertiary dropdown-toggle dropdown-toggle-split"
												data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
												@if (!item.boolnCalendarIsChangeable.Value) { <text> disabled </text> }>
											<span class="sr-only"></span>
										</button>
										<span class="dropdown-menu">
											<a class="dropdown-item availability checkbox-label"
											   data-intPkResource="@item.intPk" data-boolIsCalendar="true"
											   data-boolnIsAvailable="null" href="#">Calendarized</a>
										</span>
									}
								}
								else
								{
									<button id="" data-intPkResource="@item.intPk" data-strName="@item.strName"
											class="btn btn-tertiary resourceCalendarButton">
										<i class="fa fa-calendar"></i>
									</button>
									<button type="button" class="btn btn-tertiary dropdown-toggle dropdown-toggle-split"
											data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
											@if (!item.boolnCalendarIsChangeable.Value) { <text> disabled </text> }>
										<span class="sr-only">Toggle Dropdown</span>
									</button>
									<span class="dropdown-menu">
										<a class="dropdown-item availability checkbox-label"
										   data-intPkResource="@item.intPk" data-boolIsCalendar="false"
										   data-boolnIsAvailable="true" href="#">Available/Unavailable</a>
									</span>
								}
							</span>
							@*@if (item.boolnIsCalendar.Value == true && (Model.objResponse.boolIDeviceToolOrCustom))
								{
									<button class="btn btn-info btn-sm ml-2 addResourceTime"
											data-intPk-strName="@item.intPk|@item.strName|@item.strUnit">
										<i class="fa fa-clock-o" aria-hidden="true"></i>
									</button>
								}*@
							<button class="btn btn-primary ml-2 addCost"
									data-intPk-strName="@item.intPk|@item.strName|@item.boolnCostIsChangeable.Value"
									data-boolIsDeviceToolOrCustom="@Model.objResponse.boolIDeviceToolOrCustom">
								<i class="fa fa-usd" aria-hidden="true"></i>
							</button>
						}
						@if (Model.objResponse.arrpePathElement[0].strName != "Custom Resources")
						{
							<button class="btn btn-secondary ml-2 editResourceOrTemplate" data-intPk="@item.intPk"
									data-boolIsDeviceToolOrCustom="@Model.objResponse.boolIDeviceToolOrCustom">
								<i class="fa fa-pencil" aria-hidden="true"></i>
							</button>
						}

						<button class="btn btn-danger ml-2 deleteResource" data-intPkResource="@item.intPk">
							<i class="fa fa-trash-o"></i>
						</button>
					</span>
				</li>
			}
		</ul>
		@*<hr/>*@
		<br />
	}
	if (Model.objResponse.arrres.Count > 0)
	{
		<h3>Resources</h3>
		<ul class="list-group">
			@foreach (var item in Model.objResponse.arrres)
			{
				<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action
                    cursor-pointer">
					<a class="col-sm-9 pt-3 pb-3 my-resources"
					   asp-controller="PrintshopResourcesTemplate"
					   asp-action="GetTemplatesAndResources"
					   asp-route-intPk="@item.intPk"
					   asp-route-boolIsType="@item.boolIsType">@item.strName</a>
					<input type="hidden" value="@item.intPk|@item.boolIsType" id="intPkResource" />
					<span class="">
						@if (Model.objResponse.boolIsPhysical)
						{
							<span class="btn-group">
								@if (!item.boolnIsCalendar.Value && item.boolnIsAvailable != null)
								{
									<span class="btn btn-tertiary checkbox-switch switchAvailability pl-0 pb-0"
										  data-intPkResource="@item.intPk" data-printshopid="@strPrintshopId">
										<div class="switch-plate resAvailability">
											<div class="switch@(item.boolnIsAvailable.Value ? " on" : "")"
												 id="resource-switch-@item.intPk" data-on="Available"
												 data-off="Unavailable">
											</div>
										</div><label><i class="fa fa-database"></i></label>
									</span>
									@if (Model.objResponse.boolIDeviceToolOrCustom)
									{
										<button type="button" class="btn btn-tertiary dropdown-toggle dropdown-toggle-split"
												data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
												@if (!item.boolnCalendarIsChangeable.Value) { <text> disabled </text> }>
											<span class="sr-only"></span>
										</button>
										<span class="dropdown-menu">
											<a class="dropdown-item availability checkbox-label"
											   data-intPkResource="@item.intPk" data-boolIsCalendar="true"
											   data-boolnIsAvailable="null" href="#">Calendarized</a>
										</span>
									}
								}
								else
								{
									<button id="" data-intPkResource="@item.intPk" data-strName="@item.strName"
											class="btn btn-tertiary resourceCalendarButton">
										<i class="fa fa-calendar"></i>
									</button>
									<button type="button" class="btn btn-tertiary dropdown-toggle dropdown-toggle-split"
											data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
											@if (!item.boolnCalendarIsChangeable.Value) { <text> disabled </text> }>
										<span class="sr-only"></span>
									</button>
									<span class="dropdown-menu">
										<a class="dropdown-item availability checkbox-label"
										   data-intPkResource="@item.intPk" data-boolIsCalendar="false"
										   data-boolnIsAvailable="true" href="#">Available/Unavailable</a>
									</span>
								}
							</span>
							@if (item.boolnIsCalendar.Value == true && (Model.objResponse.boolIDeviceToolOrCustom))
							{
								<button class="btn btn-info ml-2 addResourceTime"
										data-intPk-strName="@item.intPk|@item.strName|@item.strUnit">
									<i class="fa fa-clock-o" aria-hidden="true"></i>
								</button>
							}
							<button class="btn btn-primary ml-2 addCost"
									data-intPk-strName="@item.intPk|@item.strName|@item.boolnCostIsChangeable.Value"
									data-boolIsDeviceToolOrCustom="@Model.objResponse.boolIDeviceToolOrCustom">
								<i class="fa fa-usd" aria-hidden="true"></i>
							</button>
						}
						@if (Model.objResponse.arrpePathElement[0].strName != "Custom Resources")
						{
							<button class="btn btn-secondary ml-2 editResourceOrTemplate" data-intPk="@item.intPk"
									data-boolIsDeviceToolOrCustom="@Model.objResponse.boolIDeviceToolOrCustom">
								<i class="fa fa-pencil" aria-hidden="true"></i>
							</button>
						}

						<button class="btn btn-danger ml-2 deleteResource" data-intPkResource="@item.intPk">
							<i class="fa fa-trash-o"></i>
						</button>
					</span>
				</li>
			}
		</ul>
	}

	<div class="row">
		@if (Model.objResponse.arrpePathElement[0].strName != "Custom Resources")
		{
			<div class="col-lg-12 text-center">
				<br /><a id="addSpecificResource" value="xjdf" class="btn btn-info" href="">
					<i class="fa fa-plus-circle"></i> Add Resource
				</a>
			</div>
		}
		else
		{
			<div class="col-lg-12 text-center">
				<br />
				<button value="custom" class="btn btn-info addResourceTemplate" data-toggle="modal" data-target="#xjdfTemplateModal">
					<i class="fa fa-plus-circle"></i> Add Custom Resource
				</button>
			</div>
		}
	</div>


	<!-- Cost Modal -->
	await Html.RenderPartialAsync("~/Views/Shared/ResourceCostAndTimeModalPartialView.cshtml");

	<!-- Resource's Rule's Modal -->
	<div class="modal fade" id="calendarModal">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">

				<!-- Modal Header -->
				<div class="modal-header">
					<h3 class="modal-title" id="resourceRuleTittle">Resource's Unavailability's Rules</h3>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>

				<!-- Modal body -->
				<div class="modal-body" id="calendarModalBody">

				</div>

				<!-- Modal footer -->
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>

			</div>
		</div>
	</div>

	<!-- AddRule Confirmation Modal -->
	<div class="modal fade" id="addRuleConfirmationModal">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">

				<!-- Modal Header -->
				<div class="modal-header">
					<h4 class="modal-title">Warning</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>

				<!-- Modal body -->
				<div class="modal-body" id="addRuleConfirmationModalBody">
				</div>

				<!-- Modal footer -->
				<div class="modal-footer">
					<button type="button" class="btn btn-success" data-dismiss="modal" id="addRuleConfirmationButton"><i class="fa fa-plus-circle"> Add Anyway</i></button>
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
				</div>

			</div>
		</div>
	</div>

	@if (
		Model.objResponse.arrpePathElement[0].strName == "Custom Resources"
		)
	{
		<!-- Modal -->
		<div id="xjdfTemplateModal" class="modal fade" tabindex="-1" role="dialog">
			<div class="modal-dialog modal-md modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<h3 class="modal-title" id="res-modal-title">Add Custom Resource</h3>
						<button class="btn-sm close" type="button" data-dismiss="modal">
							<i class="fa fa-close"></i>
						</button>
					</div>
					<div class="modal-body" id="res-modal-body">
						<div id="addCustomResourceSection" hidden></div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-primary" id="saveResForm" style="display: none">Save</button>
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					</div>
				</div>
			</div>
		</div>
	}
}
else
{
	<div class="alert alert-danger" role="alert">
		@Model.strUserMessage
	</div>
}

Odyssey2Frontend/Views/PrintshopResourcesTemplate/ResourceTypesPartialView.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor;
@model List<Odyssey2Frontend.Models.ResourceModel>;

@{
	String strPrintshopName = HttpContextAccessor.HttpContext.Session.GetString("strPrintshopName");
	String strPrintshopId = HttpContextAccessor.HttpContext.Session.GetString("strPrintshopId");
}

<div class="col-md-12" id="myResourcesBody">
	<div>
        <h3 class="mt-4 mb-4">Resources Groups</h3>
	</div>
	<div class="accordion" id="myResourcesAccordion">
		@if (String.IsNullOrEmpty(strPrintshopId))
		{
			<div class="alert alert-info text-center">
				The Printshop needs to be selected.
			</div>
		}
		else if (
			Model != null &&
			Model.Count > 0
		)
		{
			int intElement = 1;
			foreach (var item in Model)
			{
				<div class="card">
					<div class="card-header">
						<a class="btn btn-link btn-sm my-resources type" id="link_@item.intPk"
						   asp-controller="PrintshopResourcesTemplate"
						   asp-action="GetTemplatesAndResources"
						   asp-route-intPk="@item.intPk"
						   asp-route-boolIsType="@item.boolIsType">@item.strTypeId</a>
						<input type="hidden" value="@item.intPk|@item.boolIsType" id="intPkResource" />
						@*<button class="btn btn-info btn-sm pull-right addResourceDefaultCalculation" data-toggle="modal" data-target="#defaulCalculationModal">Default Calculations</button>*@
					</div>
				</div>
				intElement = intElement + 1;
			}
		}
		else
		{
			<div class="alert alert-danger text-center">
				No resources added.
			</div>
		}
	</div>
</div>